CREATE DATABASE optiondata;

CREATE TABLE `fullday` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `underlying_symbol` varchar(10) DEFAULT NULL,
  `quote_date` date DEFAULT NULL,
  `root` varchar(10) DEFAULT NULL,
  `expiration` date DEFAULT NULL,
  `strike` decimal(10,4) DEFAULT NULL,
  `option_type` char(1) DEFAULT NULL,
  `open` decimal(10,4) DEFAULT NULL,
  `high` decimal(10,4) DEFAULT NULL,
  `low` decimal(10,4) DEFAULT NULL,
  `close` decimal(10,4) DEFAULT NULL,
  `trade_volume` int(11) DEFAULT NULL,
  `bid_size_1545` int(11) DEFAULT NULL,
  `bid_1545` decimal(20,4) DEFAULT NULL,
  `ask_size_1545` int(11) DEFAULT NULL,
  `ask_1545` decimal(20,4) DEFAULT NULL,
  `underlying_bid_1545` decimal(10,4) DEFAULT NULL,
  `underlying_ask_1545` decimal(10,4) DEFAULT NULL,
  `bid_size_eod` int(11) DEFAULT NULL,
  `bid_eod` decimal(20,4) DEFAULT NULL,
  `ask_size_eod` int(11) DEFAULT NULL,
  `ask_eod` decimal(20,4) DEFAULT NULL,
  `underlying_bid_eod` decimal(10,4) DEFAULT NULL,
  `underlying_ask_eod` decimal(10,4) DEFAULT NULL,
  `vwap` text,
  `open_interest` int(11) DEFAULT NULL,
  `delivery_code` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_date` (`quote_date`),
  KEY `idx_expiration` (`expiration`),
  KEY `idx_underlying` (`underlying_symbol`),
  KEY `idx_type` (`option_type`)
) ENGINE=InnoDB AUTO_INCREMENT=970286 DEFAULT CHARSET=utf8;

CREATE TABLE `optiondata` (
  `underlying_symbol` varchar(10) DEFAULT NULL,
  `quote_date` date DEFAULT NULL,
  `root` varchar(10) DEFAULT NULL,
  `expiration` date DEFAULT NULL,
  `strike` decimal(10,4) DEFAULT NULL,
  `option_type` char(1) DEFAULT NULL,
  `open` decimal(10,4) DEFAULT NULL,
  `high` decimal(10,4) DEFAULT NULL,
  `low` decimal(10,4) DEFAULT NULL,
  `close` decimal(10,4) DEFAULT NULL,
  `trade_volume` int(11) DEFAULT NULL,
  `bid_size_1545` int(11) DEFAULT NULL,
  `bid_1545` decimal(10,4) DEFAULT NULL,
  `ask_size_1545` int(11) DEFAULT NULL,
  `ask_1545` decimal(10,4) DEFAULT NULL,
  `underlying_bid_1545` decimal(10,4) DEFAULT NULL,
  `underlying_ask_1545` decimal(10,4) DEFAULT NULL,
  `bid_size_eod` int(11) DEFAULT NULL,
  `bid_eod` decimal(20,4) DEFAULT NULL,
  `ask_size_eod` int(11) DEFAULT NULL,
  `ask_eod` decimal(20,4) DEFAULT NULL,
  `underlying_bid_eod` decimal(10,4) DEFAULT NULL,
  `underlying_ask_eod` decimal(10,4) DEFAULT NULL,
  `vwap` text,
  `open_interest` int(11) DEFAULT NULL,
  `delivery_code` varchar(100) DEFAULT NULL,
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `iv` decimal(65,30) DEFAULT NULL,
  `delta` decimal(65,30) DEFAULT NULL,
  `theta` decimal(65,30) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_date` (`quote_date`),
  KEY `idx_expiration` (`expiration`),
  KEY `idx_underlying` (`underlying_symbol`),
  KEY `idx_type` (`option_type`),
  KEY `idx_iv` (`iv`)
) ENGINE=InnoDB AUTO_INCREMENT=33045398 DEFAULT CHARSET=utf8;
